### ISSUE TITLE
Could not find traina2ctmp.txt file?

### ISSUE THREAD

**Issue by mahfuj9346449** [yhldhit/WMMD-Caffe#1]
Can you provide this file?

tmpfile: "/home/hsi/mmd-caffe/data/amazon_to_caltech/traina2ctmp.txt"

layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "fc8_office"
  bottom: "label"
  loss_param {
    ignore_label: -1
	trainfile: "/home/hsi/mmd-caffe/data/amazon_to_caltech/traina2c.txt"
	#训练数据集，最好用绝对路径比如：
	tmpfile: "/home/hsi/mmd-caffe/data/amazon_to_caltech/traina2ctmp.txt"
	#一个临时文件，,可以先建一个空文件
	num_of_source:958
	#源域上面的样本总数
	num_of_target:1123
	#目标域上的样本总数
	batch_size:1123
	#跟上面测试阶段的batch_size保持一致
	#把test阶段的shuffle改为0；
	#另外数据集（比如traina2c.txt）一定要先是source数据，然后是target数据；
	target_lambda: 1e-5
  }
}

**Comment by yhldhit** [comment]
You can create an empty file and name it as 'traina2ctmp.txt' in this directory '/home/hsi/mmd-caffe/data/amazon_to_caltech/'.
