### ISSUE TITLE
data_constructor.py is not working.

### ISSUE THREAD

**Issue by mahfuj1093** [yhldhit/WMMD-Caffe#2]
I changed the path:  os.chdir("/home/hsi/mmd-caffe/images"), but its not working. Can you fix it please?

**Comment by yhldhit** [comment]
Hi, this file helps iteratively read the directory and help construct our dataset. To use this file, you need to fdownload the images before using. When running, you need to specify source and target domain. 
Did replace the directory "/home/hsi/mmd-caffe/images" with the path you store the images. Besides, this directory should have subdirectories and the name of these subdirectories should represent domains, such as amazon, webcam and so on. In these subdirectories, let's say amazon, there will be sub-subdirectory where the name of these directories imply the classes, such as back_pack and so on. Thus, the absolute path of an image from the back_pack will be like:
 /home/hsi/mmd-caffe/images/amazon/back_pack/frame_0001.jpg.
I also did some modification for this file for the sake of simplification. 
Let me know if you got more question.

**Comment by mahfuj9346449** [comment]
Thank you so much. Now it's working. But It creates txt file consisiting only 10 classes. I want to make list consisting of 31 classes. For an example : source domain : amazon and target domain: dslr. What should I do ?

**Comment by yhldhit** [comment]
You are welcome. I pre-defined some dictionary which contains all the classes. If you want to use the 31 classes, you need change the third line of the code from 'Dict = gl.partDict;'　to 'Dict = gl.Dict;'

**Comment by mahfuj9346449** [comment]
Thank you again. It works.
