### ISSUE TITLE
Could not create log file: No such file or directory COULD NOT CREATE LOGFILE '20170707-050753.4076'

### ISSUE THREAD

**Issue by mahfuj9346449** [yhldhit/WMMD-Caffe#3]
**Please can you tell us why this message shows during training?** 

I0707 05:07:53.087152  4076 net.cpp:68] Memory required for data: 0
I0707 05:07:53.087191  4076 layer_factory.hpp:74] Creating layer data
I0707 05:07:53.087210  4076 net.cpp:85] Creating Layer data
I0707 05:07:53.087218  4076 net.cpp:339] data -> data
I0707 05:07:53.087236  4076 net.cpp:339] data -> label
I0707 05:07:53.087251  4076 net.cpp:339] data -> weight
I0707 05:07:53.087261  4076 net.cpp:114] Setting up data
I0707 05:07:53.087266  4076 image_data_layer.cpp:37] Opening file /home/mahfuj/WMMD-Caffe/data/amazon_to_webcam/testa2w.txt
I0707 05:07:53.087427  4076 image_data_layer.cpp:56] A total of 295 images.
I0707 05:07:53.088889  4076 image_data_layer.cpp:85] output data size: 1123,3,227,227
I0707 05:07:53.135136  4076 base_data_layer.cpp:43] Initializing prefetch
I0707 05:07:53.135215  4076 base_data_layer.cpp:45] Prefetch initialized.
I0707 05:07:53.135265  4076 net.cpp:121] Top shape: 1123 3 227 227 (173601201)
I0707 05:07:53.135273  4076 net.cpp:121] Top shape: 1123 2 (2246)
I0707 05:07:53.135278  4076 net.cpp:121] Top shape: 10 (10)
I0707 05:07:53.135282  4076 net.cpp:127] Memory required for data: 694413828
I0707 05:07:53.135303  4076 layer_factory.hpp:74] Creating layer label_data_1_split
I0707 05:07:53.135326  4076 net.cpp:85] Creating Layer label_data_1_split
I0707 05:07:53.135334  4076 net.cpp:381] label_data_1_split <- label
I0707 05:07:53.135349  4076 net.cpp:339] label_data_1_split -> label_data_1_split_0
I0707 05:07:53.135365  4076 net.cpp:339] label_data_1_split -> label_data_1_split_1
I0707 05:07:53.135380  4076 net.cpp:339] label_data_1_split -> label_data_1_split_2
I0707 05:07:53.135390  4076 net.cpp:339] label_data_1_split -> label_data_1_split_3
Could not create log file: No such file or directory
COULD NOT CREATE LOGFILE '20170707-050753.4076'!

**Comment by yhldhit** [comment]
You may need to pre-create a directory named 'log' in the directory 'WMMD-Caffe'

**Comment by mahfuj9346449** [comment]
Yes, It fixed. Thank you very much.
