### ISSUE TITLE
MMDLoss layer of WMMD-caffe cannot work with new virsion of caffe? Can you update this layer for current caffe please? I found this error when I tried to compile caffe with MMDLoss layer.

### ISSUE THREAD

**Issue by mahfuj9346449** [yhldhit/WMMD-Caffe#5]
src/caffe/layers/mmd_layer.cpp: In instantiation of ‘void caffe::MMDLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/mmd_layer.cpp:119:1:   required from here
src/caffe/layers/mmd_layer.cpp:17:18: error: ‘const class caffe::MMDParameter’ has no member named ‘num_of_kernel’
   num_of_kernel_ = this->layer_param_.mmd_param().num_of_kernel();
                  ^
src/caffe/layers/mmd_layer.cpp:18:15: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lambda’
   mmd_lambda_ = this->layer_param_.mmd_param().mmd_lambda();
               ^
src/caffe/layers/mmd_layer.cpp:19:18: error: ‘const class caffe::MMDParameter’ has no member named ‘iter_of_epoch’
   iter_of_epoch_ = this->layer_param_.mmd_param().iter_of_epoch();
                  ^
src/caffe/layers/mmd_layer.cpp:22:11: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lr’
   mmd_lr_ = this->layer_param_.mmd_param().mmd_lr();
           ^
src/caffe/layers/mmd_layer.cpp:23:16: error: ‘const class caffe::MMDParameter’ has no member named ‘quad_weight’
   quad_weight_ = this->layer_param_.mmd_param().quad_weight();
                ^
src/caffe/layers/mmd_layer.cpp:24:13: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lock’
   mmd_lock_ = this->layer_param_.mmd_param().mmd_lock();//specify when the weights of each layer need update
             ^
src/caffe/layers/mmd_layer.cpp:25:14: error: ‘const class caffe::MMDParameter’ has no member named ‘num_class’
   num_class_ = this->layer_param_.mmd_param().num_class();
              ^
src/caffe/layers/mmd_layer.cpp:26:15: error: ‘const class caffe::MMDParameter’ has no member named ‘test_inter’
   test_inter_ = this->layer_param_.mmd_param().test_inter();
               ^
src/caffe/layers/mmd_layer.cpp:27:20: error: ‘const class caffe::MMDParameter’ has no member named ‘total_iter_test’
   total_iter_test_ = this->layer_param_.mmd_param().total_iter_test();
                    ^
src/caffe/layers/mmd_layer.cpp:52:46: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   if(this->layer_param_.mmd_param().method() == "max"){
                                              ^
src/caffe/layers/mmd_layer.cpp:54:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:56:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "none"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:59:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "L2"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:61:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:62:19: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         I_lambda_ = this->layer_param_.mmd_param().method_param().i_lambda();
                   ^
src/caffe/layers/mmd_layer.cpp:64:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "max_ratio"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:65:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:68:13: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   LOG(INFO) << this->layer_param_.mmd_param().method() << " num: " << method_number_;
             ^
src/caffe/layers/mmd_layer.cpp:94:19: error: ‘const class caffe::MMDParameter’ has no member named ‘entropy_thresh’
   entropy_thresh_ = this->layer_param_.mmd_param().entropy_thresh();//for every sample
                   ^
src/caffe/layers/mmd_layer.cpp: In instantiation of ‘void caffe::MMDLossLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/mmd_layer.cpp:119:1:   required from here
src/caffe/layers/mmd_layer.cpp:17:18: error: ‘const class caffe::MMDParameter’ has no member named ‘num_of_kernel’
   num_of_kernel_ = this->layer_param_.mmd_param().num_of_kernel();
                  ^
src/caffe/layers/mmd_layer.cpp:18:15: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lambda’
   mmd_lambda_ = this->layer_param_.mmd_param().mmd_lambda();
               ^
src/caffe/layers/mmd_layer.cpp:19:18: error: ‘const class caffe::MMDParameter’ has no member named ‘iter_of_epoch’
   iter_of_epoch_ = this->layer_param_.mmd_param().iter_of_epoch();
                  ^
src/caffe/layers/mmd_layer.cpp:22:11: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lr’
   mmd_lr_ = this->layer_param_.mmd_param().mmd_lr();
           ^
src/caffe/layers/mmd_layer.cpp:23:16: error: ‘const class caffe::MMDParameter’ has no member named ‘quad_weight’
   quad_weight_ = this->layer_param_.mmd_param().quad_weight();
                ^
src/caffe/layers/mmd_layer.cpp:24:13: error: ‘const class caffe::MMDParameter’ has no member named ‘mmd_lock’
   mmd_lock_ = this->layer_param_.mmd_param().mmd_lock();//specify when the weights of each layer need update
             ^
src/caffe/layers/mmd_layer.cpp:25:14: error: ‘const class caffe::MMDParameter’ has no member named ‘num_class’
   num_class_ = this->layer_param_.mmd_param().num_class();
              ^
src/caffe/layers/mmd_layer.cpp:26:15: error: ‘const class caffe::MMDParameter’ has no member named ‘test_inter’
   test_inter_ = this->layer_param_.mmd_param().test_inter();
               ^
src/caffe/layers/mmd_layer.cpp:27:20: error: ‘const class caffe::MMDParameter’ has no member named ‘total_iter_test’
   total_iter_test_ = this->layer_param_.mmd_param().total_iter_test();
                    ^
src/caffe/layers/mmd_layer.cpp:52:46: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   if(this->layer_param_.mmd_param().method() == "max"){
                                              ^
src/caffe/layers/mmd_layer.cpp:54:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:56:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "none"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:59:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "L2"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:61:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:62:19: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         I_lambda_ = this->layer_param_.mmd_param().method_param().i_lambda();
                   ^
src/caffe/layers/mmd_layer.cpp:64:51: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   else if(this->layer_param_.mmd_param().method() == "max_ratio"){
                                                   ^
src/caffe/layers/mmd_layer.cpp:65:16: error: ‘const class caffe::MMDParameter’ has no member named ‘method_param’
         top_k_ = this->layer_param_.mmd_param().method_param().top_num();
                ^
src/caffe/layers/mmd_layer.cpp:68:13: error: ‘const class caffe::MMDParameter’ has no member named ‘method’
   LOG(INFO) << this->layer_param_.mmd_param().method() << " num: " << method_number_;
             ^
src/caffe/layers/mmd_layer.cpp:94:19: error: ‘const class caffe::MMDParameter’ has no member named ‘entropy_thresh’
   entropy_thresh_ = this->layer_param_.mmd_param().entropy_thresh();//for every sample
                   ^
Makefile:575: recipe for target '.build_release/src/caffe/layers/mmd_layer.o' failed
make: *** [.build_release/src/caffe/layers/mmd_layer.o] Error 1

**Comment by yhldhit** [comment]
Other configuring files should be changed accordingly. I will update our version ASAP.
