### ISSUE TITLE
为什么include目录下没有include/caffe/layers文件夹呢？导致许多layer都没有.hpp文件，无法编译

### ISSUE THREAD

**Issue by mengchuangji** [yhldhit/WMMD-Caffe#7]
您可以提供一下吗？

**Comment by yhlhit** [comment]
你好，层的定义在wmmd/src/caffe/layers 目录下，头文件在wmmd/include/caffe 目录下。

**Comment by yhlhit** [comment]
> 您可以提供一下吗？

你好，层的定义在wmmd/src/caffe/layers 目录下，头文件在wmmd/include/caffe 目录下。

**Comment by mengchuangji** [comment]
![default](https://user-images.githubusercontent.com/24237829/53781691-c6f85400-3f44-11e9-915a-469dff6d1780.png)
wmmd/include/caffe 的头文件不够，还有许多其他层的呢，比如wmmd的头文件呢

**Comment by mengchuangji** [comment]
一些放基本层的头文件 如batch_norm,accuracy等  所在的layers文件夹呢。其他caffe源码都有include/caffe/layers 这个目录  此处没有

**Comment by yhldhit** [comment]
> 一些放基本层的头文件 如batch_norm,accuracy等 所在的layers文件夹呢。其他caffe源码都有include/caffe/layers 这个目录 此处没有

头文件不是每个层一个文件 都放大一起了 wmmd的定义在neuro_layers 里面。

**Comment by mengchuangji** [comment]
请问一下，CGAL库必须自己安装吗？

**Comment by yhldhit** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        是的，官网有安装的方法。
        
    
        
            
        
    
    
        
        

        
    

    在2019年3月7日 11:41，kind-hearted-Tbag<notifications@github.com> 写道： 


请问一下，CGAL库必须自己安装吗？

**Comment by mengchuangji** [comment]
请问一下，train_val.prototxt中的batch_size对结果影响大吗？比如目标域的batch_size一定要设置成样本总数吗（比如，caltech256的为1123）.但对于一些大网络，如googleNet,会out of memory.有时对于小网络，如AlexNet也一样。如果batch_size设置的小一些，accuracy会波动非常大，您遇到过吗？还有，为什么slover.prototxt的test_iter要设置为1呢，一般情况下，不是为样本总数吗（比如，caltech256的为1123）。

**Comment by kind-hearted-Tbag** [comment]
请问在进行31类的实验时，出现softmax_loss_layers.cu:95, file not exist in softmax的错误，是哪里出现问题了呢？

**Comment by mengchuangji** [comment]
做31类的实验时，出现I0319 17:00:44.124846 11013 image_data_layer.cpp:179] Transform time: 17.718 ms. *** stack smashing detected ***: ./build/tools/caffe terminated。 请问该怎么解决呢？

**Comment by yhlhit** [comment]
测试的数据集为batch_size*test_iter，所以batch_size 为测试集大小时，test_iter 就是1.
其他问题我没碰到过，你是现在还没跑通过代码吗？还是只有部分数据集有这个问题。


| |
yhl
|
|
yhllearner@163.com
|
签名由网易邮箱大师定制
在2019年3月19日 11:46，kind-hearted-Tbag<notifications@github.com> 写道：

请问一下，train_val.prototxt中的batch_size对结果影响大吗？比如目标域的batch_size一定要设置成样本总数吗（比如，caltech256的为1123）.但对于一些大网络，如googleNet,会out of memory.有时对于小网络，如AlexNet也一样。如果batch_size设置的小一些，accuracy会波动非常大，您遇到过吗？还有，为什么slover.prototxt的test_iter要设置为1呢，一般情况下，不是为样本总数吗（比如，caltech256的为1123）。

**Comment by mengchuangji** [comment]
都跑通了，accuracy有时波动比较大，比如70%，一会儿90%。还有就是跑31类实验的时候，能改的都改了，但还是有问题。我改了class_num，fc8_office层的num_output，此外mmd-fc7,8 的num_of_kernel，num_class，entropy_thresh都要设置为31吗  ？  这些我都改了，还需要动哪儿吗？mmd layer.cu也重新编译了，但是出现I0319 17:00:44.124846 11013 image_data_layer.cpp:179] Transform time: 17.718 ms. *** stack smashing detected ***: ./build/tools/caffe terminated。

**Comment by yhlhit** [comment]
accuracy波动不会这么大。你说的stack smashing detected 这个问题我好像没遇到过，不过mmd_layer 里面需要把源域每类样本数改一下，把对应的源域取消注释即可，可以看看是不是这个问题。      


| |
yhl
|
|
yhllearner@163.com
|
签名由网易邮箱大师定制
在2019年3月19日 17:34，kind-hearted-Tbag<notifications@github.com> 写道：

都跑通了，accuracy有时波动比较大，比如70%，一会儿90%。还有就是跑31类实验的时候，能改的都改了，但还是有问题。我改了class_num，fc8_office层的num_output，此外mmd-fc7,8 的num_of_kernel，num_class，entropy_thresh都要设置为31吗 ？ 这些我都改了，还需要动哪儿吗？mmd layer.cu也重新编译了，但是出现I0319 17:00:44.124846 11013 image_data_layer.cpp:179] Transform time: 17.718 ms. *** stack smashing detected ***: ./build/tools/caffe terminated。

**Comment by mengchuangji** [comment]
嗯 mmd_layer 我都改过 我再找找其他的问题，谢谢！
